---
# https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
- name: install kubernetes
  dnf:
    name:
      - kubelet-1.28.2
      - kubeadm-1.28.2
      - kubectl-1.28.2
    disable_excludes: kubernetes
    state: present
    update_cache: yes
  notify: Daemon Reload
- name: enable kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started
- name: Get kubectl completion
  shell: kubectl completion bash
  register: kubectl_completion_script
  changed_when: false
- name: Create kubectl completion script file
  file:
    path: /etc/bash_completion.d/kubectl
    state: touch
    mode: a+r
    modification_time: preserve
    access_time: preserve
- name: Retrieve kubectl completion script content
  slurp:
    src: /etc/bash_completion.d/kubectl
  register: kubectl_completion_script_file
- name: Write kubectl completion script
  copy:
    dest: /etc/bash_completion.d/kubectl
    content: "{{ kubectl_completion_script.stdout }}"
  when: kubectl_completion_script.stdout != kubectl_completion_script_file.content
- name: Write kubectl profile script
  copy:
    dest: /etc/profile.d/kubectl.sh
    content: |
      alias k=kubectl
      complete -o default -F __start_kubectl k
    mode: a+r
- name: Add node IP in kubelet config
  lineinfile:
    path: /etc/sysconfig/kubelet
    regexp: '^KUBELET_EXTRA_ARGS='
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }} --cloud-provider=external
    state: present
    create: yes
    mode: a+r
