---
- name: add docker centos repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    gpgcheck: yes
    state: present
- name: add kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+$', '\\1') }}/rpm/"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+$', '\\1') }}/rpm/repodata/repomd.xml.key"
    state: present
    exclude:
      - kubelet
      - kubeadm
      - kubectl
      - cri-tools
      - kubernetes-cni
