---
- name: Cilium installation block
  block:

  - name: Add cilium helm repository
    kubernetes.core.helm_repository:
      name: cilium
      repo_url: "https://helm.cilium.io/"

  - name: Retreive cilium CNI version
    shell: curl -s https://raw.githubusercontent.com/cilium/cilium/main/stable.txt
    register: cilium_version
    changed_when: false

  - name: Install cilium chart
    kubernetes.core.helm:
      name: cilium
      namespace: kube-system
      chart_ref: cilium/cilium
      chart_version: "{{ cilium_version.stdout }}"
      values:
        ipv4NativeRoutingCIDR: "{{ cilium_native_routing_cidr }}"
        rollOutCiliumPods: true
        autoDirectNodeRoutes: true
        routingMode: native
        kubeProxyReplacement: true
        bpf:
          masquerade: true
        k8sServiceHost: "{{ kube_endpoint }}"
        k8sServicePort: 6443
        hubble:
          relay:
            enabled: false
          ui:
            enabled: false
            frontend:
              server:
                ipv6:
                  enabled: false
          tls:
            auto:
              enabled: true
              method: cronJob
      timeout: 10m

  become: no
