---
- name: Retreive cilium hubble last version
  shell: curl -s https://raw.githubusercontent.com/cilium/hubble/master/stable.txt
  register: version
  changed_when: false
- name: Download cilium hubble
  get_url:
    url: https://github.com/cilium/hubble/releases/download/{{ version.stdout }}/hubble-linux-amd64.tar.gz
    checksum: sha256:https://github.com/cilium/hubble/releases/download/{{ version.stdout }}/hubble-linux-amd64.tar.gz.sha256sum
    dest: /tmp/cilium-linux-{{ version.stdout }}.tar.gz
  when: ansible_architecture == "x86_64"
- name: Extract cilium hubble
  unarchive:
    src: /tmp/cilium-linux-{{ version.stdout }}.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes
