---
- name: Retreive cilium CLI last version
  shell: curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
  register: version
  changed_when: false
- name: Download cilium CLI
  get_url:
    url: https://github.com/cilium/cilium-cli/releases/download/{{ version.stdout }}/cilium-linux-amd64.tar.gz
    checksum: sha256:https://github.com/cilium/cilium-cli/releases/download/{{ version.stdout }}/cilium-linux-amd64.tar.gz.sha256sum
    dest: /tmp/cilium-linux-{{ version.stdout }}.tar.gz
  when: ansible_architecture == "x86_64"
- name: Extract cilium CLI
  unarchive:
    src: /tmp/cilium-linux-{{ version.stdout }}.tar.gz
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes
