apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp.fullname" . }}-pubkeys
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
data:
{{- range $name, $user := .Values.users }}
  {{ if $user.sshPublicKey -}}{{ $name }}: {{ $user.sshPublicKey | b64enc }}{{ end }}
{{- end }}
{{- if .Values.sshHostKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp.fullname" . }}-privatekeys
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
data:
  {{- if .Values.sshHostKeys.ed25519 }}
  ssh_host_ed25519_key: |
    {{- .Values.sshHostKeys.ed25519 | b64enc | nindent 4 }}
  {{- end }}
  {{- if .Values.sshHostKeys.rsa }}
  ssh_host_rsa_key: |
    {{- .Values.sshHostKeys.rsa | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
