apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Ti
  storageClassName: proxmox-data
