apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
