apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
stringData:
  USER: {{ .Values.username }}
  PASS: {{ .Values.password }}
