---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}bt-ui
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
{{- if gt (default 0 .Values.env.PEERPORT) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}bt-peer
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.env.PEERPORT }}
      nodePort: {{ .Values.env.PEERPORT }}
      protocol: UDP
      name: {{ .Values.env.PEERPORT }}-udp
    - port: {{ .Values.env.PEERPORT }}
      nodePort: {{ .Values.env.PEERPORT }}
      protocol: TCP
      name: {{ .Values.env.PEERPORT }}-tcp
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
{{- end }}