name: Ansible install
inputs:
  default-private-key:
    description: 'SSH private key'
    required: true
    type: string
  default-ssh-user:
    description: 'SSH user'
    default: 'root'
    type: string
  default-ssh-port:
    description: 'SSH port'
    default: 22
    type: number
  default-ssh-ip:
    description: 'SSH IP'
    default: 'localhost'
    type: string
runs:
  using: "composite"
  steps:
  - name: Set up Python 3.11
    uses: actions/setup-python@v4
    with:
      python-version: 3.11
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install ansible
    shell: bash
  - name: set ansible config secrets
    env:
      SSH_PRI: ${{ inputs.default-private-key }}
    run: |
      mkdir ~/.ssh
      echo "$SSH_PRI" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
    shell: bash
  - name: set default settings
    shell: bash
    env:
      SSH_USR: ${{ inputs.default-ssh-user }}
      SSH_PORT: ${{ inputs.default-ssh-port }}
      SSH_IP: ${{ inputs.default-ssh-ip }}
    run: |
      cat << EOF > ~/.ansible.cfg
      [defaults]
      inventory = $(pwd)/ansible/hosts.yml
      remote_user = ${SSH_USR}
      remote_port = ${SSH_PORT}
      host_key_checking = False
      interpreter_python = auto_silent
      [privilege_escalation]
      become = True
      [ssh_connection]
      ssh_common_args = "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -p ${SSH_PORT} -W %h:%p -q ${SSH_USR}@${SSH_IP}'"
      EOF
