- name: Get admin k8s SA cert
  hosts: kube_first_cp
  become: no
  tasks:
  - name: Get the Secret object of the admin service account
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ ansible_user }}"
      namespace: kube-system
    register: secret
  - name: Output the cert secret to GitHub
    debug:
      var: secret.resources[0].data["ca.crt"] | b64decode
