---
- name: Install Kubernetes requirements
  hosts: kube
  roles:
    - kube/requirements

- name: Init Kubernetes cluster
  hosts: kube_cp
  vars:
    kube_endpoint: "{{ lookup('env','K8S_ENDPOINT') }}"
  roles:
    - kube/init

- name: Join Kubernetes cluster
  hosts: kube:!kube_first_cp
  serial: 1
  roles:
    - kube/join

- name: Install Cilium
  hosts: kube_first_cp
  roles:
    - kube/cilium
  vars:
    kube_endpoint: "{{ lookup('env','K8S_ENDPOINT') }}"
    cilium_native_routing_cidr: "{{ lookup('env','K8S_POD_CIDR') }}"

- name: Install administrative tools
  hosts: kube_adm
  roles:
    - kube/admin

- name: Wait for Kubernetes cluster to be ready
  hosts: localhost
  tasks:
    - pause:
        seconds: 120

- name: Set UP CSI plugin
  hosts: kube_first_cp
  vars:
    proxmox_url: "{{ lookup('env','PROXMOX_URL') }}"
    proxmox_ccm_token_id: "{{ lookup('env','PROXMOX_CCM_TOKEN_ID') }}"
    proxmox_ccm_token_secret: "{{ lookup('env','PROXMOX_CCM_TOKEN_SECRET') }}"
    proxmox_csi_token_id: "{{ lookup('env','PROXMOX_CSI_TOKEN_ID') }}"
    proxmox_csi_token_secret: "{{ lookup('env','PROXMOX_CSI_TOKEN_SECRET') }}"
  roles:
    - kube/proxmox-csi-plugin
