apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  storageClassName: proxmox-data
