- name: Save Kubernetes VMs
  hosts: proxmox
  vars:
    comment: "{{ lookup('env','COMMENT') }}"
  tasks:
    - name: Retrieve list of kube VMs
      shell: |
        grep -irn "^name: kube" /etc/pve/qemu-server|awk -F[/.] '{print $5}'
      register: vms
      changed_when: false
    - debug:
        var: vms.stdout_lines
    - name: Backup VMs
      loop: "{{ vms.stdout_lines }}"
      shell: vzdump {{ item }} --mode stop --compress lzo --storage local --remove 1 --maxfiles 2 --notes-template "{{ comment }}"
      args:
        executable: /usr/bin/bash
      register: result
      changed_when: result.rc == 254
      failed_when: result.rc != 254 and result.rc != 0
