apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kavita.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "kavita.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{ if and .Values.mangaManager.enabled .Values.mangaManager.env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kavita.fullname" . }}-manga-manager-env
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "kavita.mangaManager.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.mangaManager.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{ if .Values.mangaManager.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kavita.fullname" . }}-manga-manager-config
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "kavita.mangaManager.labels" . | nindent 4 }}
data:
  config.ini: |-
    [main]
    cache_cover_images = True

{{- end }}
