{{- if not .Values.storage.config.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "kavita.fullname" . }}-config"
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "kavita.labels" . | nindent 4 }}
  {{- if not .Values.storage.config.deleteOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  storageClassName: {{ .Values.storage.config.storageClass }}
  accessModes:
    - {{ .Values.storage.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
{{- end }}
{{- if and .Values.mangaManager.enabled (not .Values.mangaManager.storage.config.existingClaim) -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "kavita.fullname" . }}-manga-manager-folder"
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "kavita.mangaManager.labels" . | nindent 4 }}
  {{- if not .Values.mangaManager.storage.config.deleteOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  storageClassName: {{ .Values.storage.config.storageClass }}
  accessModes:
    - {{ .Values.mangaManager.storage.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mangaManager.storage.config.size }}
{{- end }}
