name: Docker - Build rsync
on:
  workflow_dispatch:
#  schedule:
#    - cron: "05 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: docker/rsync
        push: true
        tags: "${{ secrets.DOCKERHUB_USERNAME }}/rsync:latest"
