name: K8S - Install Ingress-Nginx Controller
on:
  workflow_dispatch:
#  workflow_call:
#  schedule:
#    - cron: "44 4 * * *"
#  push:
#    paths:
#      - '.github/workflows/k8s-ingress-nginx-install.yml'


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - uses: ./.github/workflows/action-login-kubectl
      name: Launch kubectl installation
      with:
        token: ${{ secrets.K8S_ADM_TOKEN_SECRET }}
        server: ${{ secrets.K8S_ENDPOINT_EXTERNAL }}
        cert: ${{ secrets.K8S_ADM_CERT_SECRET }}
    - name: Install Ingress-Nginx Controller
      run: |
        helm upgrade --install ingress-nginx ingress-nginx \
        --repo https://kubernetes.github.io/ingress-nginx \
        --namespace ingress-nginx --create-namespace \
        --set controller.service.externalIPs[0]=${{ secrets.OVH_VIRTUAL_IP }} \
        --set controller.service.nodePorts.http=${{ secrets.K8S_INGRESS_NGINX_HTTP_PORT }} \
        --set controller.service.nodePorts.https=${{ secrets.K8S_INGRESS_NGINX_HTTPS_PORT }}
