name: Setup - 08 - Configure pfSense
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Setup - 07 - Deploy pfSense workflow]
    types: [completed]
jobs:
  configure-pfsense:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - uses: ./.github/workflows/action-install-ansible
      name: Launch ansible installation
      with:
        default-private-key: ${{ secrets.ADM_SSH_PRIVATE_KEY }}
        default-ssh-user: ${{ secrets.ADM_NAME }}
        default-ssh-port: ${{ secrets.PFSENSE_SSH_PORT }}
        default-ssh-ip: ${{ secrets.OVH_VIRTUAL_IP }}
    - name: Retrieve pfSense XML configuration file
      run: |
        mkdir /tmp/pfsense
        ansible-playbook ansible/playbooks/ansible/playbook-ansible-fetch-file.yml \
        -e remote=pfsense \
        -e source=/cf/conf/config.xml \
        -e destination=/tmp/pfsense/
    - name: Install lxml prerequisites for edit XML files
      run: pip install lxml
    - name: Edit XML configuration file
      run: ansible-playbook ansible/playbooks/pfsense/playbook-pfsense-configuration.yml
    - name: Push pfSense XML configuration file
      run: |
        ansible-playbook ansible/playbooks/ansible/playbook-ansible-copy-file.yml \
        -e remote=pfsense \
        -e source=/tmp/pfsense/config.xml \
        -e destination=/cf/conf/ \
        -e user=root \
        -e grp=wheel \
        -e permissions=0644
    - name: Save configuration
      run: ansible-playbook ansible/playbooks/pfsense/playbook-pfsense-save-conf.yml
